Added CASLS retainer agreement
LemmaLegalConsulting/docassemble-GBLSLetters pull request #15
Opened 2024-02-02 21:19 UTC by h-mcguire

This PR adds the docx and yml for the CASLS retainer agreement. It also makes necessary adjustments to attachment, objects, and bundles to produce document as output. 

I also removed the attachment block from one of the yml for the plain_langauge_retainer per the Lemma Style Guide.

2024-02-06 16:01 UTC, miabonardi requested changes
Great work here. 

A few things: 

1. Down the CASLS letter path only, after collecting signatures, it collects addresses which are not used on output document. I don't think this should be happening. Maybe try looking into why these are being triggered?

2. The header and logo are overlapping and should be adjusted 
![Screen Shot 2024-02-06 at 10 59 24 AM](https://github.com/LemmaLegalConsulting/docassemble-GBLSLetters/assets/65858862/0e8bd7d1-e793-4c8f-a286-57d1f17a2bb1)

3. Logo in bottom corner is getting cut off
![Screen Shot 2024-02-06 at 11 00 27 AM](https://github.com/LemmaLegalConsulting/docassemble-GBLSLetters/assets/65858862/42df90e7-0f4b-437c-81ac-d7ec9d307fd9)

2024-02-20 12:58 UTC, miabonardi requested changes
Progress here. 

Did you test these changes? 

I ran into an error after selecting CASLS as document: 

![Screen Shot 2024-02-20 at 7 55 17 AM](https://github.com/LemmaLegalConsulting/docassemble-GBLSLetters/assets/65858862/0ca20e94-4e9d-432c-8a5b-f11d99d3ddff)

You'll need to change the order block to make the `[i]` be `[0]`. If you need more than 1 client or attorney, you'll want to do a `clients.gather()`

2024-02-20 14:21 UTC, h-mcguire commented
I must have totally not tested this - sorry for committing broken code. I was trying to fix the ordering and gather problem (it's gathering the address's for attorney and client after signatures and without me asking for it in any code I wrote). I tried to do it by changing how complete_attribute for attorneys and clients was implemented. I used the [i] based on how the process was discussed in the documentation [here](https://docassemble.org/docs/groups.html#list%20of%20objects).  

I tried to just have complete_attribute defined only within the individual .yml but it didn't fix the gathering issue.

2024-02-20 14:38 UTC, miabonardi commented
No worries! 

You're working on an interview order block, and the link you sent is a question block (which is why they are working differently for you). 

Check out how I've edited the example you're looking at to do something similar to what you're going for. You can run this in the playground by creating a new project, and naming the yml file. 

```
objects:
  - location: |
      DAList.using(
        object_type=Address,
        there_are_any=True)
---
# main interview order
# only 1 mandatory True
mandatory: True
code: |
  location.gather()
  download
---
event: download
question: |
  The locations
subquestion: |
  % for loc in location:
  * ${ loc }
  % endfor
---
question: |
  What is the address of the
  ${ ordinal(i) } location?
fields:
  - Address: location[i].address
  - Unit: location[i].unit
    required: False
  - City: location[i].city
  - State: location[i].state
    code: |
      states_list()
  - Zip: location[i].zip
    required: False
---
question: |
  Would you like to add another location?
yesno: location.there_is_another
```

For troubleshooting why its asking for address even when the interview order and the template do not ask for it, on the page it asks for it, select developer information and scroll to the bottom and see why it's being called. A zip code might be required on download in AL, but we can figure it out if this is causing your issue.

2024-02-20 15:33 UTC, h-mcguire commented
Thanks! I think it is about the download in AL. It calls CASLS_Retainer_Agreement['final'] and then looks for the clients address set that includes zip. For each variable in the set the interview would look for the object with "_label" after. 

So it looked for clients[0].address.address and pulled up the question block that gathers that, then it looked for clients[0].address.address_label. Then it moved to another variable from the set doing the same thing, ending on clients[0].address.zip_label.  Not sure if this is helpful or makes sense.

2024-02-20 15:49 UTC, miabonardi commented
Can you commit the code that was getting this error?

2024-02-20 16:09 UTC, h-mcguire commented
Just committed! The address gather problem also happens when you try to do other documents, see the no contact letter for a quick example. 

In the CASLS Retainer there is also a problem where it seems like it is gathering legal_problems before clients[0].name.full despite it being after the name gather. Or more specifically, legal_problems use of ${ clients[0].name } is what triggers the name gather.  If you click the dev mode when it gathers name it makes it seem like legal_problems is what triggers the question - not the main order block.

2024-02-20 19:31 UTC, miabonardi commented
@nonprofittechy Is there a way to disable the collection of an address on download or preset it in AL?

2024-02-20 20:10 UTC, nonprofittechy commented
Yes, look for the store_variable_snapshot line that is calling for users[0].address.zip

2024-02-20 20:33 UTC, miabonardi commented
That's what I thought it was too, but couldn't find it when I looked. Will try again

2024-02-20 21:17 UTC, nonprofittechy commented
> That's what I thought it was too, but couldn't find it when I looked. Will try again

You can also use the icon in the playground to browse through mentions of any reference to users[0].address.address, and of course try the developer information button `</>` in the browser when you're running the interview.

![image](https://github.com/LemmaLegalConsulting/docassemble-GBLSLetters/assets/7645641/46ff2f60-45c0-4cf4-ad2a-388f827b4819)

2024-02-20 21:28 UTC, miabonardi commented
I did that for `store_variable_snapshot` and found nothing. For `users[0].address.address` and `users[0].address.zip` only mentions are coming in from `ql_baseline.yml`. I wonder if something in the [al_visual file](docassemble/GBLSLetters/data/questions/al_visual.yml) could be causing this? Should this file be in this repo?

2024-02-20 22:50 UTC, tobyfey commented
With GBLS, I also had users[0].address.address being called when it wasn't in the interview or the templates.  It would be called during document production, so I assumed it was in the documents, and later realized it wasn't (after I added a code block that set it to GBLS main office).

2024-03-18 20:07 UTC, nonprofittechy commented on setup.py
> +      long_description='# docassemble.GBLS\r\n\r\nLetter Suite for Greater Boston Legal Services.\r\n\r\n## Author\r\n\r\nStavros Constantinou, sconsta@bu.edu\r\n\r\n',
```suggestion
      long_description='# docassemble.GBLSLetters\r\n\r\nLetter Suite for Greater Boston Legal Services.\r\n\r\n## Author\r\n\r\nStavros Constantinou, sconsta@bu.edu\r\n\r\n',
```

2024-03-18 20:10 UTC, merged